const words = [
  { undercover: "王心凌", normal: "张韶涵" },
  { undercover: "四喜丸子", normal: "鱼香肉丝" },
  { undercover: "橘子", normal: "橙子" },
  { undercover: "龙凤胎", normal: "双胞胎" },
  { undercover: "薯片", normal: "饼干" },
  { undercover: "海狮", normal: "海豚" },
  { undercover: "猪肉脯", normal: "牛肉干" },
  { undercover: "非诚勿扰", normal: "天天向上" },
  { undercover: "榴莲", normal: "菠萝蜜" },
  { undercover: "老天爷", normal: "老佛爷" },
  { undercover: "周立波", normal: "郭德纲" },
  { undercover: "隐形眼镜", normal: "近视眼镜" },
  { undercover: "香辣牛肉面", normal: "红烧牛肉面" },
  { undercover: "狄仁杰", normal: "包青天" },
  { undercover: "宋小宝", normal: "小沈阳" },
  { undercover: "井底之蛙", normal: "鼠目寸光" },
  { undercover: "李湘", normal: "谢娜" },
  { undercover: "豆浆", normal: "牛奶" },
  { undercover: "碧螺春", normal: "铁观音" },
  { undercover: "电动车", normal: "自行车" },
  { undercover: "四面楚歌", normal: "十面埋伏" },
  { undercover: "花样男子", normal: "流星花园" },
  { undercover: "甩干机", normal: "干洗机" },
  { undercover: "金丝猴", normal: "大白兔" },
  { undercover: "努尔哈赤", normal: "成吉思汗" },
  { undercover: "生菜", normal: "白菜" },
  { undercover: "工藤新一", normal: "福尔摩斯" },
  { undercover: "灰姑娘", normal: "丑小鸭" },
  { undercover: "魔法师", normal: "魔术师" },
  { undercover: "光棍节", normal: "情人节" },
];

module.exports = words;
